# Generated by Django 2.0.6 on 2018-07-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_booklanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklanguage',
            name='book_instance',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='book_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookLanguage'),
        ),
    ]
